name: 🦀 Publish Crate

on:
  schedule:
    - cron: "0 0 * * 1,4"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      updated: ${{ steps.version-check.outputs.updated }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - uses: actions-rust-lang/setup-rust-toolchain@02be93da58aa71fb456aa9c43b301149248829d8 # v1.15.1

      - run: cargo run
        id: version-check

  publish:
    needs: [check]
    if: needs.check.outputs.updated == 'true'
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        working-directory: build/crates
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - uses: actions-rust-lang/setup-rust-toolchain@02be93da58aa71fb456aa9c43b301149248829d8 # v1.15.1

      - run: cargo run
        working-directory: ${{ github.workspace }}

      - run: cargo test

      - uses: rust-lang/crates-io-auth-action@e919bc7605cde86df457cf5b93c5e103838bd879 # v1.0.1
        id: auth

      - run: cargo publish --allow-dirty
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
