name: 🦀 Publish Crate

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - run: cargo run
        id: version-check

      - run: cargo test
        working-directory: ./build/crates
        if: steps.version-check.outputs.skip != 'true'

      - uses: rust-lang/crates-io-auth-action@v1
        id: auth
        if: steps.version-check.outputs.skip != 'true'

      - run: cargo publish --allow-dirty
        working-directory: ./build/crates
        if: steps.version-check.outputs.skip != 'true'
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
